export const siteConfig = {
  name: "Codox - Developer Portfolio",
  authorName: "Codox",
  username: "codox",
  description:
    "Codox's - From custom websites to automation and email systems — We help you streamline your business so you can focus on what you do best.",
  url: "https://codox-portfolio.netlify.app",
  links: {
    twitter: "",
    github: "",
  },
  ogImage: "https://codox-portfolio.netlify.app/profile-img.jpg",
  iconIco:
    "https://res.cloudinary.com/dbfvcn3f6/image/upload/v1692357384/assets/naman-favicon.ico",
  logoIcon:
    "https://res.cloudinary.com/dbfvcn3f6/image/upload/v1692357294/assets/naman-logo.png",
  keywords: [
    "Codox",
    "Creative Tech Agency",
    "Web Developer Portfolio",
    "Next.js portfolio template",
    "React portfolio template",
    "Developer portfolio template",
    "Portfolio website template",
    "Next.js template",
    "Modern portfolio website",
    "Frontend developer portfolio",
    "Creative Tech Agency portfolio",
    "Open source portfolio template",
    "Web developer portfolio template",
    "Responsive portfolio template",
    "React.js portfolio",
    "Tailwind CSS portfolio",
    "Developer showcase template",
    "Free portfolio template",
    "Next.js 13 template",
    "Shadcn UI template",
    "Career timeline template",
    "Portfolio with dark mode",
    "GitHub portfolio template",
  ],
};
